---
title       : Presentation Sninyapp
subtitle    : Coursera Data Product course
author      : Romain PHILIPPE
job         : Student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---


## The subject

The goal of this small app is to display information about a baseball player according to their name.
The informations come from the ***Hitters*** dataset. We have the salary, the number of hits, the league name, the division names ...<br><br>
We also display a histogram which represents the frequency salary. A red line indicate the salary of the selectioned player. So we can compare the différence of salary 


--- .class #id 

## The input of the app

There is only one input in this app : the names of the player. To do that we load the ISLR package.
```{r}
library(ISLR)
playersNames<-row.names(Hitters)
head(substr(playersNames, 2, nchar(playersNames)),20)
```

Then, we compute two small command to extract the name of the player in remove the first character (-). We can see the R script above.

--- .class #id 

## The output of the app

There two main output of this app : <br>

1. A histogram plot
2. A table

The histogram represents the density salary off all the players. We display two line : one for the median of the salary and the other one is the current salary. <br>
A table display information about the player like : number of hits, number of runs, the league name and the division name.


--- .class #id 


## Conclusion

In the slidify presentation, I use a ***selectInput*** as an input and two differents outputs : an histogram (plotOutput) and a table (dataTableOutput). 

